export default {
    GET_USER: 'GET_USER',
    GET_PAGE_DATA: 'GET_PAGE',
    SET_PAGE_TITLE: 'SET_PAGE_TITLE',
    SET_PAGE_THUMBNAIL: 'SET_PAGE_THUMBNAIL',
    SET_PAGE_CONTENT: 'SET_PAGE_CONTENT',
    SET_PAGE_THUMBNAIL: 'SET_PAGE_THUMBNAIL'
}